defaults: &defaults
  host: "mongo"
  allow_dynamic_fields: false
  include_root_in_json: true
  parameterize_keys: true
  persist_in_safe_mode: true

development:
  <<: *defaults
  database: "vowessly"

test:
  <<: *defaults
  database: "vowessly_test"

cucumber:
  <<: *defaults
  database: "vowessly_cucumber"

# set these environment variables on your prod server
production:
  <<: *defaults
  uri: <%= ENV['MONGOHQ_URL'] %>
